### ISSUE TITLE
Energy content definition

### ISSUE THREAD

**Issue by kiselevnightkeo** [bendudson/freegs#64]
What is the right definition of energy content from the equilibrium pressure?

W=3/2 int( p_eq dV )  ?

**Comment by bendudson** [comment]
Hi @kiselevnightkeo Sorry for the delay. Yes I think that should be correct. There is also energy content from the magnetic energy. 
I'm closing this because the main repository is now https://github.com/freegs-plasma/freegs. Please add issues there, or let me know if you'd like to be added to a Slack group.
